"""Small-LLM-generated acknowledgements via Ollama.

Replaces the categorical ack for a single turn with a 3–7 word response
generated by a local small model (default ``gemma3:4b``) that's been
given a tight system prompt + the user's transcript. Result: the ack
actually speaks to what was said ("Right, scanning the inbox." vs. a
generic "Let me check") without any of the brain's cost.

Stateless by design — we intentionally don't feed conversation history
here. The brain already owns that; the ack just needs to name what's
being acknowledged. If Ollama is slow, unreachable, or returns anything
that smells wrong, we return None and the caller falls back to the
categorical pool.
"""

from __future__ import annotations

import json
import logging
import os
import re
import urllib.error
import urllib.request
from typing import Optional

logger = logging.getLogger(__name__)

_OLLAMA_URL = os.environ.get("HOPE_OLLAMA_URL", "http://localhost:11434")
_MODEL = os.environ.get("HOPE_ACK_MODEL", "gemma3:4b")
# Hard timeout — if the small model can't reply in this long, the
# categorical fallback is already better than a stuck speak thread.
_TIMEOUT_SEC = float(os.environ.get("HOPE_ACK_TIMEOUT", "2.5"))

_SYSTEM = (
    "You are Hope's brief acknowledgement oracle. You receive a single "
    "voice turn from the user and return a short acknowledgement that "
    "Hope would say IMMEDIATELY while still thinking about the full reply.\n\n"
    "Hope's voice: warm British woman, dry-witted, composed, never "
    "apologetic, never performative. Loyal to her user ('sir'). "
    "Occasionally playful but never theatrical. Never ends with '!'.\n\n"
    "LENGTH — this is the most-broken rule so read it twice:\n"
    "- Target **4 to 7 words**. 5 is ideal.\n"
    "- Never 1, 2, or 3 words. \"On it.\" / \"Right.\" / \"Got it.\" are "
    "  ALL TOO SHORT. The user needs enough sound to feel Hope heard "
    "  them, without overlapping her full reply which arrives seconds "
    "  later. One- or two-word replies feel clipped and robotic.\n"
    "- Never more than 9 words.\n\n"
    "Other rules:\n"
    "- Reply with ONLY the acknowledgement. No quotes, no labels, no "
    "  explanation. Natural speech, not 'I will...' scaffolding.\n"
    "- Don't answer the request — only acknowledge it. The full answer "
    "  comes from a separate system afterwards.\n"
    "- If the turn is just a wake word ('hope', 'hey hope'), reply with "
    "  a short greeting still in the 4–7 word range, e.g. 'Yes sir, "
    "  what can I do?' or 'Right here — what's up?'\n"
    "- If the turn is gibberish or unclear, ask for a repeat, e.g. "
    "  'Sorry, could you say that again?'\n\n"
    "Examples (count the words):\n"
    "  open the calculator        → On it — one moment, sir.            (6)\n"
    "  what time is it            → Let me check the clock.             (5)\n"
    "  tell me a joke             → Oh, we're doing jokes now?          (5)\n"
    "  summarise my emails        → Right, scanning the inbox now.      (5)\n"
    "  close JMP and quit Chrome  → Closing both of those now.          (5)\n"
    "  play some background music → Putting something on for you.       (5)\n"
    "  what's on the screen       → Right, taking a look now.           (5)\n"
    "  hey hope                   → Yes sir, what can I do?             (6)\n"
    "  um                         → Sorry, could you say that again?    (6)\n"
    "  thanks                     → Anytime, sir. Always glad to help.  (7)\n"
)


def _looks_plausible(text: str) -> bool:
    """Reject obvious model slop — hallucinated scaffolding, long rambles."""
    if not text:
        return False
    # No quoting, no role labels, no markdown.
    if any(tok in text.lower() for tok in ("ack:", "hope:", "user:", "```",
                                            "acknowledgement:", "response:")):
        return False
    # Length: enforce the 4–9 word band so Hope doesn't clip to "On it."
    # or ramble. Strip trailing punctuation before counting so "On it." +
    # "On it" are judged the same.
    words = [w for w in text.replace(",", " ").replace(".", " ").split() if w]
    if len(words) < 4 or len(words) > 9:
        return False
    # No sentence-final exclamation — against Hope's voice contract.
    if text.strip().endswith("!"):
        return False
    # Strip common model wrappers like outer quotes.
    return True


def _strip(text: str) -> str:
    t = text.strip()
    # Strip paired surrounding quotes.
    if (t.startswith('"') and t.endswith('"')) or \
       (t.startswith("'") and t.endswith("'")):
        t = t[1:-1].strip()
    # Strip markdown asterisks that sometimes slip in.
    t = re.sub(r"^\*+|\*+$", "", t).strip()
    return t


def gen_ack(transcript: str, *, timeout: Optional[float] = None) -> Optional[str]:
    """Ask the local Ollama model for an ack. Returns None on any failure.

    Hard contract: this function MUST NOT raise, MUST NOT block beyond
    ``timeout`` seconds (default ``HOPE_ACK_TIMEOUT``), and MUST return
    ``None`` rather than a bad ack so the categorical fallback kicks in.
    """
    if not transcript or not transcript.strip():
        return None
    payload = {
        "model": _MODEL,
        "system": _SYSTEM,
        "prompt": transcript.strip(),
        "stream": False,
        "options": {
            # Higher temp for genuine variety; 20 tokens ≈ 7–9 words,
            # leaving headroom for the filter's 9-word ceiling.
            "temperature": 0.9,
            "num_predict": 20,
            "top_p": 0.9,
        },
    }
    req = urllib.request.Request(
        f"{_OLLAMA_URL.rstrip('/')}/api/generate",
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout or _TIMEOUT_SEC) as resp:
            body = json.loads(resp.read())
    except (urllib.error.URLError, TimeoutError, ConnectionError) as exc:
        logger.debug("gemma ack: request failed: %s", exc)
        return None
    except Exception as exc:  # noqa: BLE001
        logger.debug("gemma ack: unexpected failure: %s", exc)
        return None

    raw = _strip(body.get("response", ""))
    if not _looks_plausible(raw):
        logger.debug("gemma ack: implausible output rejected: %r", raw)
        return None
    return raw


__all__ = ["gen_ack"]
